# Generated by Django 4.2.3 on 2024-12-01 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=30)),
                ('idade', models.CharField(max_length=30)),
                ('peso', models.FloatField()),
                ('qtd_vacinas', models.IntegerField()),
                ('dono_do_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
